package model;
// Generated 24 ene. 2021 16:24:16 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Accesos generated by hbm2java
 */
@Entity
@Table(name = "accesos", catalog = "trenes")
public class Accesos implements java.io.Serializable {

	private int codAcceso;
	private Estaciones estaciones;
	private String desc;

	public Accesos() {
	}

	public Accesos(int codAcceso, Estaciones estaciones, String desc) {
		this.codAcceso = codAcceso;
		this.estaciones = estaciones;
		this.desc = desc;
	}

	@Id

	@Column(name = "cod_acceso", unique = true, nullable = false)
	public int getCodAcceso() {
		return this.codAcceso;
	}

	public void setCodAcceso(int codAcceso) {
		this.codAcceso = codAcceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_estacion", nullable = false)
	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	@Column(name = "desc", nullable = false, length = 50)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}
