package model;
// Generated 24 ene. 2021 16:24:16 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lineas generated by hbm2java
 */
@Entity
@Table(name = "lineas", catalog = "trenes")
public class Lineas implements java.io.Serializable {

	private int codLinea;
	private String nombre;
	private Set<LineaEstacion> lineaEstacions = new HashSet<LineaEstacion>(0);
	private Set<MisTrenes> misTreneses = new HashSet<MisTrenes>(0);

	public Lineas() {
	}

	public Lineas(int codLinea, String nombre) {
		this.codLinea = codLinea;
		this.nombre = nombre;
	}

	public Lineas(int codLinea, String nombre, Set<LineaEstacion> lineaEstacions, Set<MisTrenes> misTreneses) {
		this.codLinea = codLinea;
		this.nombre = nombre;
		this.lineaEstacions = lineaEstacions;
		this.misTreneses = misTreneses;
	}

	@Id

	@Column(name = "cod_linea", unique = true, nullable = false)
	public int getCodLinea() {
		return this.codLinea;
	}

	public void setCodLinea(int codLinea) {
		this.codLinea = codLinea;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lineas")
	public Set<LineaEstacion> getLineaEstacions() {
		return this.lineaEstacions;
	}

	public void setLineaEstacions(Set<LineaEstacion> lineaEstacions) {
		this.lineaEstacions = lineaEstacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lineas")
	public Set<MisTrenes> getMisTreneses() {
		return this.misTreneses;
	}

	public void setMisTreneses(Set<MisTrenes> misTreneses) {
		this.misTreneses = misTreneses;
	}

	@Override
	public String toString() {
		return "Lineas [codLinea=" + codLinea + ", nombre=" + nombre + ", lineaEstacions=" + lineaEstacions
				+ ", misTreneses=" + misTreneses.toString() + "]";
	}
	
}
