package model;
// Generated 24 ene. 2021 16:24:16 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LineaEstacionId generated by hbm2java
 */
@Embeddable
public class LineaEstacionId implements java.io.Serializable {

	private int codLinea;
	private int codEstacion;

	public LineaEstacionId() {
	}

	public LineaEstacionId(int codLinea, int codEstacion) {
		this.codLinea = codLinea;
		this.codEstacion = codEstacion;
	}

	@Column(name = "cod_linea", nullable = false)
	public int getCodLinea() {
		return this.codLinea;
	}

	public void setCodLinea(int codLinea) {
		this.codLinea = codLinea;
	}

	@Column(name = "cod_estacion", nullable = false)
	public int getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(int codEstacion) {
		this.codEstacion = codEstacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LineaEstacionId))
			return false;
		LineaEstacionId castOther = (LineaEstacionId) other;

		return (this.getCodLinea() == castOther.getCodLinea()) && (this.getCodEstacion() == castOther.getCodEstacion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodLinea();
		result = 37 * result + this.getCodEstacion();
		return result;
	}

}
