package model;
// Generated 24 ene. 2021 12:39:39 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lineas generated by hbm2java
 */
@Entity
@Table(name="lineas"
    ,catalog="proyecto"
)
public class Lineas implements java.io.Serializable {

	private int codLinea;
	private String nombre;
	private Set<LineaEstacion> lineaEstacions = new HashSet<LineaEstacion>(0);
	private Set<Trenes> treneses = new HashSet<Trenes>(0);

	public Lineas() {
	}

	public Lineas(int codLinea, String nombre) {
		this.codLinea = codLinea;
		this.nombre = nombre;
	}

	public Lineas(int codLinea, String nombre, Set<LineaEstacion> lineaEstacions, Set<Trenes> treneses) {
		this.codLinea = codLinea;
		this.nombre = nombre;
		this.lineaEstacions = lineaEstacions;
		this.treneses = treneses;
	}

	@Id

	@Column(name = "cod_linea", unique = true, nullable = false)
	public int getCodLinea() {
		return this.codLinea;
	}

	public void setCodLinea(int codLinea) {
		this.codLinea = codLinea;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lineas")
	public Set<LineaEstacion> getLineaEstacions() {
		return this.lineaEstacions;
	}

	public void setLineaEstacions(Set<LineaEstacion> lineaEstacions) {
		this.lineaEstacions = lineaEstacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lineas")
	public Set<Trenes> getTreneses() {
		return this.treneses;
	}

	public void setTreneses(Set<Trenes> treneses) {
		this.treneses = treneses;
	}

}
