package model;
// Generated 24 ene. 2021 12:39:39 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Trenes generated by hbm2java
 */
@Entity
@Table(name = "trenes", catalog = "trenes")
public class Trenes implements java.io.Serializable {

	private int codTren;
	private Cocheras cocheras;
	private Lineas lineas;
	private String nombre;
	private String tipo;

	public Trenes() {
	}

	public Trenes(int codTren, Cocheras cocheras, Lineas lineas, String nombre, String tipo) {
		this.codTren = codTren;
		this.cocheras = cocheras;
		this.lineas = lineas;
		this.nombre = nombre;
		this.tipo = tipo;
	}

	@Id

	@Column(name = "cod_tren", unique = true, nullable = false)
	public int getCodTren() {
		return this.codTren;
	}

	public void setCodTren(int codTren) {
		this.codTren = codTren;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_cochera", nullable = false)
	public Cocheras getCocheras() {
		return this.cocheras;
	}

	public void setCocheras(Cocheras cocheras) {
		this.cocheras = cocheras;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_linea", nullable = false)
	public Lineas getLineas() {
		return this.lineas;
	}

	public void setLineas(Lineas lineas) {
		this.lineas = lineas;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "tipo", nullable = false, length = 20)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
