package com.model;
// Generated 24 ene. 2021 15:49:25 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cocheras generated by hbm2java
 */
@Entity
@Table(name = "cocheras", catalog = "trenes")
public class Cocheras implements java.io.Serializable {

	private int codCochera;
	private String nombre;
	private String direccion;
	private Set<Trenes> treneses = new HashSet<Trenes>(0);

	public Cocheras() {
	}

	public Cocheras(int codCochera, String nombre, String direccion) {
		this.codCochera = codCochera;
		this.nombre = nombre;
		this.direccion = direccion;
	}

	public Cocheras(int codCochera, String nombre, String direccion, Set<Trenes> treneses) {
		this.codCochera = codCochera;
		this.nombre = nombre;
		this.direccion = direccion;
		this.treneses = treneses;
	}

	@Id

	@Column(name = "cod_cochera", unique = true, nullable = false)
	public int getCodCochera() {
		return this.codCochera;
	}

	public void setCodCochera(int codCochera) {
		this.codCochera = codCochera;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", nullable = false, length = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cocheras")
	public Set<Trenes> getTreneses() {
		return this.treneses;
	}

	public void setTreneses(Set<Trenes> treneses) {
		this.treneses = treneses;
	}

}
