package com.model;
// Generated 24 ene. 2021 15:49:25 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estaciones generated by hbm2java
 */
@Entity
@Table(name = "estaciones", catalog = "trenes")
public class Estaciones implements java.io.Serializable {

	private int codEstacion;
	private String nombre;
	private String direccion;
	private int numaccesos;
	private int numlineas;
	private int numviajesdest;
	private int numviajesproc;
	private Set<Viajes> viajesesForEstacionDst = new HashSet<Viajes>(0);
	private Set<LineaEstacion> lineaEstacions = new HashSet<LineaEstacion>(0);
	private Set<Viajes> viajesesForEstacionOg = new HashSet<Viajes>(0);
	private Set<Accesos> accesoses = new HashSet<Accesos>(0);

	public Estaciones() {
	}

	public Estaciones(int codEstacion, String nombre, String direccion, int numaccesos, int numlineas,
			int numviajesdest, int numviajesproc) {
		this.codEstacion = codEstacion;
		this.nombre = nombre;
		this.direccion = direccion;
		this.numaccesos = numaccesos;
		this.numlineas = numlineas;
		this.numviajesdest = numviajesdest;
		this.numviajesproc = numviajesproc;
	}

	public Estaciones(int codEstacion, String nombre, String direccion, int numaccesos, int numlineas,
			int numviajesdest, int numviajesproc, Set<Viajes> viajesesForEstacionDst, Set<LineaEstacion> lineaEstacions,
			Set<Viajes> viajesesForEstacionOg, Set<Accesos> accesoses) {
		this.codEstacion = codEstacion;
		this.nombre = nombre;
		this.direccion = direccion;
		this.numaccesos = numaccesos;
		this.numlineas = numlineas;
		this.numviajesdest = numviajesdest;
		this.numviajesproc = numviajesproc;
		this.viajesesForEstacionDst = viajesesForEstacionDst;
		this.lineaEstacions = lineaEstacions;
		this.viajesesForEstacionOg = viajesesForEstacionOg;
		this.accesoses = accesoses;
	}

	@Id

	@Column(name = "cod_estacion", unique = true, nullable = false)
	public int getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(int codEstacion) {
		this.codEstacion = codEstacion;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", nullable = false, length = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "numaccesos", nullable = false)
	public int getNumaccesos() {
		return this.numaccesos;
	}

	public void setNumaccesos(int numaccesos) {
		this.numaccesos = numaccesos;
	}

	@Column(name = "numlineas", nullable = false)
	public int getNumlineas() {
		return this.numlineas;
	}

	public void setNumlineas(int numlineas) {
		this.numlineas = numlineas;
	}

	@Column(name = "numviajesdest", nullable = false)
	public int getNumviajesdest() {
		return this.numviajesdest;
	}

	public void setNumviajesdest(int numviajesdest) {
		this.numviajesdest = numviajesdest;
	}

	@Column(name = "numviajesproc", nullable = false)
	public int getNumviajesproc() {
		return this.numviajesproc;
	}

	public void setNumviajesproc(int numviajesproc) {
		this.numviajesproc = numviajesproc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estacionesByEstacionDst")
	public Set<Viajes> getViajesesForEstacionDst() {
		return this.viajesesForEstacionDst;
	}

	public void setViajesesForEstacionDst(Set<Viajes> viajesesForEstacionDst) {
		this.viajesesForEstacionDst = viajesesForEstacionDst;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estaciones")
	public Set<LineaEstacion> getLineaEstacions() {
		return this.lineaEstacions;
	}

	public void setLineaEstacions(Set<LineaEstacion> lineaEstacions) {
		this.lineaEstacions = lineaEstacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estacionesByEstacionOg")
	public Set<Viajes> getViajesesForEstacionOg() {
		return this.viajesesForEstacionOg;
	}

	public void setViajesesForEstacionOg(Set<Viajes> viajesesForEstacionOg) {
		this.viajesesForEstacionOg = viajesesForEstacionOg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estaciones")
	public Set<Accesos> getAccesoses() {
		return this.accesoses;
	}

	public void setAccesoses(Set<Accesos> accesoses) {
		this.accesoses = accesoses;
	}

}
